### ISSUE TITLE
The getter 'size' was called on null.

### ISSUE THREAD

**Issue by grayknight2** [whenSunSet/sticker-framework-flutter#1]
Sometimes I'm getting the following issue:

```
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'size' was called on null.
Receiver: null
Tried calling: size

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ElementContainerWidgetState.addElement (package:sticker_framework/element_container_widget.dart:229:64)
#2      DecorationElementContainerWidgetState.addSelectAndUpdateElement (package:sticker_framework/decoration_element_container_widget.dart:31:5)
```

**Comment by jeremy1265** [comment]
yeah me too, sometimes can but sometimes throw exception
